{{- $chartName := include "polygon-parts-manager.name" . -}}
{{- $configmapName := include "configmap.fullname" . }}
{{- $tracing := (include "common.tracing.merged" .) | fromYaml }}
{{- $metrics := (include "common.metrics.merged" .) | fromYaml }}
{{- $serviceUrls := (include "common.serviceUrls.merged" .) | fromYaml }}
{{- $db := (include "common.db.merged" .) | fromYaml }}
{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $configmapName }}
data:
  HTTP_RETRY_ATTEMPTS: {{ .Values.env.httpRetry.attempts | quote }} # TODO: use *with* template
  HTTP_RETRY_DELAY: {{ .Values.env.httpRetry.delay | quote }}
  HTTP_RETRY_RESET_TIMEOUT: {{ .Values.env.httpRetry.resetTimeout | quote }}
  DISABLE_HTTP_CLIENT_LOGS: {{ .Values.env.disableHttpClientLogs | quote }}
  CATALOG_MANAGER_URL: {{ $serviceUrls.catalogManager | quote }}
  ARRAY_SEPARATOR: {{ .Values.env.application.arraySeparator | quote }}
  CREATE_POLYGON_PARTS_TABLES_STORED_PROCEDURE: {{ .Values.env.application.createPolygonPartsTablesStoredProcedure | quote }}
  UPDATE_POLYGON_PARTS_TABLES_STORED_PROCEDURE: {{ .Values.env.application.updatePolygonPartsTablesStoredProcedure | quote }}
  ENTITY_PARTS_NAME_PREFIX: {{ .Values.env.application.entities.parts.namePrefix | quote }}
  ENTITY_PARTS_NAME_SUFFIX: {{ .Values.env.application.entities.parts.nameSuffix | quote }}
  ENTITY_POLYGON_PARTS_NAME_PREFIX: {{ .Values.env.application.entities.polygonParts.namePrefix | quote }}
  ENTITY_POLYGON_PARTS_NAME_SUFFIX: {{ .Values.env.application.entities.polygonParts.nameSuffix | quote }}
  AGGREGATION_MAX_DECIMAL_DIGITS: {{ .Values.env.application.aggregation.maxDecimalDigits | quote }}
  DB_HOST: {{ $db.host | quote }}
  DB_PORT: {{ $db.port | quote }}
  DB_NAME: {{ $db.name | quote }}
  DB_SCHEMA: {{ $db.schema | quote }}
  DB_LOGGING: {{ $db.logging | quote }}
  DB_APPNAME: {{ $db.applicationName | quote }}
  DB_ENABLE_SSL_AUTH: {{ $db.sslEnabled | quote }}
  {{- if $db.sslEnabled }}
  DB_CA_PATH: {{ $db.sslAuth.sslMountPath }}/{{ $db.sslAuth.caFileName }}
  DB_KEY_PATH: {{ $db.sslAuth.sslMountPath }}/{{ $db.sslAuth.keyFileName }}
  DB_CERT_PATH: {{ $db.sslAuth.sslMountPath }}/{{ $db.sslAuth.certFileName }}
  {{- end }}
  REQUEST_PAYLOAD_LIMIT: {{ .Values.env.requestPayloadLimit | quote }}
  RESPONSE_COMPRESSION_ENABLED: {{ .Values.env.responseCompressionEnabled | quote }}
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  LOG_PRETTY_PRINT_ENABLED: {{ .Values.env.logPrettyPrintEnabled | quote }}
  TELEMETRY_TRACING_ENABLED: {{ $tracing.enabled | quote }}
  {{- if $tracing.enabled }}
  TELEMETRY_TRACING_URL: {{ $tracing.url | quote }}
  {{- end }}
  TELEMETRY_METRICS_ENABLED: {{ $metrics.enabled | quote }}
  {{- if $metrics.enabled }}
  TELEMETRY_METRICS_INTERVAL: {{ $metrics.interval | quote }}
  TELEMETRY_METRICS_URL: {{ $metrics.url | quote }}
  {{- end }}
  npm_config_cache: /tmp/
{{- end }}
