global:
  cloudProvider: {}
  tracing: {}
  metrics: {}
  environment: {}
  serviceUrls: {}
  db: {}
  ca:
    secretName: ''
    path: '/usr/local/share/ca-certificates'
    key: 'ca.crt'

enabled: true
environment: development
replicaCount: 1
initialDelaySeconds: 60
nodePort: 30030 #for minikube deployment only
resetOnConfigChange: true
imagePullPolicy: Always

podAnnotations: {}

cloudProvider:
  dockerRegistryUrl: my-registry-url.io
  imagePullSecretName: 'my-registry-secret'
  flavor: openshift

tracing:
  enabled: false
  url: ''

metrics:
  enabled: false
  url: ''
  interval: 15000 # default interval value of telemetry package
  prometheus:
    scrape: false
    port: 8080

serviceUrls:
  catalogManager: ""

image:
  repository: polygon-parts-manager
  tag: 'latest'

env:
  port: 80
  targetPort: 8080
  protocol: TCP
  logLevel: info
  logPrettyPrintEnabled: false
  responseCompressionEnabled: true
  requestPayloadLimit: 1mb
  application:
    arraySeparator: ','
    createPolygonPartsTablesStoredProcedure: 'create_polygon_parts_tables'
    updatePolygonPartsTablesStoredProcedure: 'update_polygon_parts'
    entities:
      parts:
        namePrefix: ''
        nameSuffix: '_parts'
      polygonParts:
        namePrefix: ''
        nameSuffix: ''
  httpRetry:
    attempts: 5
    delay: exponential
    resetTimeout: 30000
  disableHttpClientLogs: true

# external
db:
  host: ''
  port: 5432
  username: ''
  password: ''
  name: ''
  schema: polygon_parts
  logging: false
  applicationName: polygon_parts
  sslEnabled: false
  sslAuth:
    sslMountPath: /mnt/db/secrets
    certFileName: postgresql.crt
    keyFileName: postgresql.key
    caFileName: root.crt
  secrets:
    useExternal: false
    externalSecretName: ''

resources:
  enabled: true
  value:
    limits:
      cpu: 0.5
      memory: 0.5Gi
    requests:
      cpu: 0.25
      memory: 0.25Gi

route:
  enabled: false
  path: /
  timeout:
    enabled: false # defaults to 30s by openshift
    duration: 60s # supported units (us, ms, s, m, h, d)
  tls:
    useCerts: false
    certificate: ''
    key: ''
    caCertificate: ''

ingress:
  enabled: false
  type: 'nginx-org' # supported values: 'nginx-org' | 'nginx-kubernetes'
  path: /
  host: 'localhost'
  cors:
    enabled: true
    origin: '*'
